site_name: Flex

repo_url: https://github.com/Makiavelo/flex

docs_dir: mkd

theme: readthedocs

dev_addr: 0.0.0.0:8000

nav:
    - Home: index.md
    - Install: install.md
    - Quick Tour: quick_tour.md
    - Examples: examples.md
    - Relations: relations.md
    - Traits: traits.md
    - Searching: searching.md
    - Event Hooks: event_hooks.md
    - Extras: extras.md